name: Contract-Verify

on:
  pull_request:
    branches: [ master ]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        npm install
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - run: |
        echo '${{ steps.files.outputs }}'
        echo '${{ steps.files.outputs.all }}'
        echo '${{ steps.files.outputs.added }}'
        echo '${{ steps.files.outputs.modified }}'
        echo '${{ steps.files.outputs.removed }}'
        echo '${{ steps.files.outputs.renamed }}'
        echo '${{ steps.files.outputs.added_modified }}'
        node index.js '${{ steps.files.outputs.added }}' '${{ steps.files.outputs.modified }}' '${{ steps.files.outputs.removed }}' '${{ steps.files.outputs.renamed }}' '${{ steps.files.outputs.added_modified }}'
    - name: Run status checks
      run: node status-checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
