name: Contract-Verify

on:
  pull_request:
    branches: [ master ]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        npm install
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - run: |
        echo "${{ steps.files.outputs }}"
    - name: Run status checks
      run: node status-checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
